import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from '@mui/material/styles';
import theme from "../theme";
import { Roboto } from "next/font/google";
import Sidebar from "./components/Sidebar";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
  subsets: ["latin"],
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <AppRouterCacheProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ display: "flex", minHeight: "100vh", flexDirection: "row" }}
      >
        <Sidebar />
        <ThemeProvider theme={theme}>
            <main style={{ flexGrow: 1, padding: '24px' }}>
              {children}
            </main>
        </ThemeProvider>
      </body>
      </AppRouterCacheProvider>
    </html>
  );
}
